name: BedWarsPlugin
main: tu.paquete.BedWarsPlugin
version: 2.1
api-version: 1.20
commands:
  bw:
    description: Comando principal de BedWars
    usage: /<command> <subcommand>
# Note: This plugin supports optional MySQL. Add MySQL credentials in config.yml
